version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.11.12.1/16

volumes:
  pgdata:
    driver: local